### ISSUE TITLE
Broken link at Download Button

### ISSUE THREAD

**Issue by donhuvy** [DevExpress-Examples/blazor-DxDataGrid-show-the-confirmation-dialog-before-deleting-a-record#4]
At this page https://www.devexpress.com/Support/Center/Example/Details/T802166/blazor-data-grid-how-to-implement-the-delete-confirmation-feature

When I press button download, this download link is broken.

**Comment by zabelin-vladimir** [comment]
Thank you for this report, I've fixed this link.
