### ISSUE TITLE
Row is not removed from grid

### ISSUE THREAD

**Issue by VinceAvery** [DevExpress-Examples/blazor-DxDataGrid-show-the-confirmation-dialog-before-deleting-a-record#6]
I downloaded and ran the sample

However when  I click delete and confirm the dialog, the row is not deleted.

I can see it is deleted in the underlying list but not removed on screen from the gird.

Any ideas?

**Comment by zabelin-vladimir** [comment]
Hello @VinceAvery 

It's necessary to use the [Refresh](https://docs.devexpress.com/Blazor/DevExpress.Blazor.Base.DxDataGridBase-1.Refresh) method to update DataGrid. I updated this example, thank you for your report.

**Comment by VinceAvery** [comment]
Thanks for fast feedback  - @zabelin-vladimir 
Have a good day!
